### ISSUE TITLE
The outline's links to individual chiasms do not work

### ISSUE THREAD

**Issue by ArtskydJ** [KayserCommentaryOrg/revelation-project#1]
https://revelation.biblicalblueprints.org/structure/explanation#the-pattern

Currently the chiasm links don't work.

**Comment by TehShrike** [comment]
Fixed in 45a4efbe90152ddeb278a384c68a929c620ec4f3

**Comment by TehShrike** [comment]
Well, sort of

**Comment by TehShrike** [comment]
Fixed slightly more in 05e6cc4ac25ef7f75b2317b252594979bbe93195
